apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  labels:
    app: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
    spec:
      containers:
      - name: distributor
        image: docker.io/murilloff/distributor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: distributor-service
spec:
  ports:
  - port: 5000
    name: tcp1
    targetPort: 5000
  - port : 5001
    name: tcp2
    targetPort: 5001
  selector:
    app: distributor
  type: ClusterIP